services:
  localstack:
    container_name: localstack_credentialIssuer
    image: localstack/localstack:4.12.0@sha256:0df3a97da57de03a588c05d9b8f390f15c7033fc7c4512f94619d344bc3cd317
    ports:
      - "4560:4566"
    environment:
      - SERVICES=dynamodb,kms,s3
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - ./localstack/provision.sh:/etc/localstack/init/ready.d/provision.sh